#pragma once

// default xml path
#define XML_PATH "/data/game_patch_cfg.xml"
#define XML_PATH_LIST "/data/game_patch_fliprate_list.xml"
// Xml Keys
#define GR1_EN "GravityRush1_English"
#define GR2_60HzKey "GravityRush2_60FPS"
#define BB_60FPSKey "Bloodborne_60FPS"
#define BB_MBKey "Bloodborne_MotionBlur"
#define BB_CAKey "Bloodborne_ChromaticAberration"
#define BB_DebugCameraKey "Bloodborne_DebugCamera"
#define BB_ColorBorder "Bloodborne_ColorBorderDiag"
#define BB_Vsync "Bloodborne_Vsync"
#define BB_1280_720 "Bloodborne_1280x720"
#define SOTC_DebugMenu "SOTC_DebugMenu"
#define TO1886_60FPS "TheOrder1886_60FPS"
#define TO1886_16_9 "TheOrder1886_16_9"
#define Big4R_MainDebugMenu "Uncharted_4_Remaster_DebugMenu"
#define Big4R_TLLDebugMenu "Uncharted_TheLostLegacy_Remaster_DebugMenu"
#define DemonSouls_UnlockFPS "DemonSouls_UnlockFPS"
#define Driveclub_60FPS "Driveclub_60FPS"
#define Driveclub_DLC_Unlock "Driveclub_UnlockAllCarsBikes"
#define TLG_60FPS "TheLastGurdian_60FPS"
#define t2ps4_109_1080p_in120Hz "TheLastOfUs2_109_Force1080p_in_120Hz"
